apiVersion: v1
kind: ReplicationController
metadata: 
  name: mysql
  namespace: go-dog
spec:
  replicas: 1
  selector:
    app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: ccr.ccs.tencentyun.com/libs/mysql:5.7
        ports: 
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"